import { Product } from './types';

export const PRODUCTS: Product[] = [
  // Ropa / Clothing
  { id: 13, name: 'Conjunto de Ropa Infantil', cat: 'Niños', department: 'Ropa', type: 'Pijama', gender: 'Niño', price: '$30.00', originalPrice: '$42.00', offer: 28, desc: 'Conjunto de ropa cómodo y moderno para niños.', image: 'https://f000.backblazeb2.com/file/jpgshared/nHEMdy_t', isOutOfStock: false, quantityRemaining: 10, quantitySold: 5, sizes: ['2-3 Años', '4-5 Años', '6-7 Años'] },
  { id: 14, name: 'Vestido Infantil Delicado', cat: 'Niños', department: 'Ropa', type: 'Vestido', gender: 'Niña', price: '$40.00', originalPrice: '$55.00', offer: 27, desc: 'Vestido de niña con un diseño suave y elegante.', image: 'https://f000.backblazeb2.com/file/jpgshared/V-ySjWju', isOutOfStock: false, quantityRemaining: 5, quantitySold: 12, sizes: ['3-4 Años', '5-6 Años', '7-8 Años'] },
  { id: 15, name: 'Zapatillas Deportivas Infantiles', cat: 'Niños', department: 'Ropa', type: 'Zapatos', gender: 'Niño', price: '$40.00', originalPrice: '$60.00', offer: 33, desc: 'Zapatos deportivos cómodos para niños.', image: 'https://f000.backblazeb2.com/file/jpgshared/8Tp1n0gw', isOutOfStock: true, quantityRemaining: 0, quantitySold: 20, sizes: ['28', '30', '32', '34'] },
  { id: 10, name: 'Vestido Femenino Moderno', cat: 'Mujeres', department: 'Ropa', type: 'Vestido', gender: 'Mujer', price: '$65.00', originalPrice: '$85.00', offer: 23, desc: 'Vestido de mujer con diseño moderno y elegante.', image: 'https://f000.backblazeb2.com/file/jpgshared/SLHTi4NY', isOutOfStock: false, quantityRemaining: 15, quantitySold: 8, sizes: ['S', 'M', 'L', 'XL'] },
  { id: 11, name: 'Falda Femenina Elegante', cat: 'Mujeres', department: 'Ropa', type: 'Vestido', gender: 'Mujer', price: '$45.00', originalPrice: '$60.00', offer: 25, desc: 'Falda elegante y cómoda para ocasiones diarias.', image: 'https://f000.backblazeb2.com/file/jpgshared/vxxlpFaA', isOutOfStock: false, quantityRemaining: 20, quantitySold: 3, sizes: ['XS', 'S', 'M', 'L'] },
  { id: 1, name: 'Camiseta de Algodón Masculina', cat: 'Hombres', department: 'Ropa', type: 'Camisetas', gender: 'Hombre', price: '$25.00', originalPrice: '$35.00', offer: 28, desc: 'Camiseta de algodón cómoda y de alta calidad, perfecta para el uso diario.', image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=800&auto=format&fit=crop', isOutOfStock: false, quantityRemaining: 50, quantitySold: 100, sizes: ['S', 'M', 'L', 'XL', 'XXL'] },
  { id: 3, name: 'Vestido Femenino de Verano', cat: 'Mujeres', department: 'Ropa', type: 'Vestido', gender: 'Mujer', price: '$60.00', originalPrice: '$80.00', offer: 25, desc: 'Vestido de verano ligero y cómodo en colores brillantes.', image: '/src/assets/images/regenerated_image_1784264399582.png', isOutOfStock: false, quantityRemaining: 10, quantitySold: 15, sizes: ['S', 'M', 'L'] },
  { id: 5, name: 'Conjunto Infantil de Juego', cat: 'Niños', department: 'Ropa', type: 'Pijama', gender: 'Niño', price: '$45.00', originalPrice: '$60.00', offer: 25, desc: 'Conjunto de algodón cómodo y elegante para niños.', image: '/src/assets/images/regenerated_image_1784264397007.png', isOutOfStock: false, quantityRemaining: 15, quantitySold: 20, sizes: ['1-2 Años', '3-4 Años'] },
  
  // Electrónica & Componentes de PC / Hardware
  { id: 20, name: 'Smartwatch Deportivo Pro Ultra', cat: 'Electrónica', department: 'Electrónica', type: 'Smartwatches', gender: 'Unisex', price: '$89.00', originalPrice: '$120.00', offer: 26, desc: 'Reloj inteligente con pantalla AMOLED de alta resolución, sensor de ritmo cardíaco, GPS y resistencia al agua.', image: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?q=80&w=800&auto=format&fit=crop', isOutOfStock: false, quantityRemaining: 18, quantitySold: 34, sizes: ['44mm', '49mm', 'Negro', 'Plata'] },
  { id: 21, name: 'Auriculares Inalámbricos Noise Cancelling Pro', cat: 'Electrónica', department: 'Electrónica', type: 'Audio & Auriculares', gender: 'Unisex', price: '$69.00', originalPrice: '$99.00', offer: 30, desc: 'Auriculares con cancelación activa de ruido, sonido Hi-Fi inmersivo y hasta 36 horas de batería con estuche de carga rápida.', image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?q=80&w=800&auto=format&fit=crop', isOutOfStock: false, quantityRemaining: 25, quantitySold: 42, sizes: ['Blanco', 'Negro Espacial'] },
  { id: 22, name: 'Smartphone Pro Max 5G (128GB/256GB)', cat: 'Electrónica', department: 'Electrónica', type: 'Smartphones', gender: 'Unisex', price: '$349.00', originalPrice: '$450.00', offer: 22, desc: 'Teléfono inteligente de alta gama con cámara triple de 108MP, pantalla fluida de 120Hz y carga ultra rápida de 67W.', image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?q=80&w=800&auto=format&fit=crop', isOutOfStock: false, quantityRemaining: 12, quantitySold: 19, sizes: ['128GB', '256GB', '512GB'] },
  { id: 23, name: 'Altavoz Bluetooth Portátil Resistente al Agua', cat: 'Electrónica', department: 'Electrónica', type: 'Audio & Auriculares', gender: 'Unisex', price: '$45.00', originalPrice: '$65.00', offer: 30, desc: 'Sonido potente 360 grados con graves profundos, batería de 20 horas y certificación IPX7 resistente a salpicaduras.', image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?q=80&w=800&auto=format&fit=crop', isOutOfStock: false, quantityRemaining: 14, quantitySold: 28, sizes: ['Negro', 'Azul Marino'] },

  // PC Components / Componentes de PC
  { id: 30, name: 'Chasis Gamer ATX Vidrio Templado + 4 Fans ARGB', cat: 'Chasis de PC', department: 'Electrónica', type: 'Chasis de PC', gender: 'General', price: '$95.00', originalPrice: '$130.00', offer: 27, desc: 'Gabinete para PC con flujo de aire optimizado, panel lateral de vidrio templado, soporte para radiadores de hasta 360mm y 4 ventiladores ARGB preinstalados.', image: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?q=80&w=800&auto=format&fit=crop', isOutOfStock: false, quantityRemaining: 8, quantitySold: 15, sizes: ['Negro', 'Blanco', 'Mesh Edition'] },
  { id: 31, name: 'Tarjeta Madre Wi-Fi 6E DDR5 PCIe 5.0 Ultra', cat: 'Tarjeta madre', department: 'Electrónica', type: 'Tarjeta madre', gender: 'General', price: '$210.00', originalPrice: '$260.00', offer: 19, desc: 'Placa base de alto rendimiento con disipadores térmicos avanzados, conectividad Wi-Fi 6E integrada, Bluetooth 5.3 y 4 ranuras M.2 NVMe.', image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=800&auto=format&fit=crop', isOutOfStock: false, quantityRemaining: 6, quantitySold: 11, sizes: ['ATX', 'Micro-ATX'] },
  { id: 32, name: 'Memoria RAM Gaming RGB DDR5 32GB (2x16GB) 6000MHz', cat: 'RAM', department: 'Electrónica', type: 'RAM', gender: 'General', price: '$129.00', originalPrice: '$169.00', offer: 24, desc: 'Kit de memoria RAM de ultra alta velocidad con disipador de aluminio y barra de luz RGB direccionable. Soporta perfiles Intel XMP 3.0 y AMD EXPO.', image: 'https://images.unsplash.com/photo-1562976540-1502c2145186?q=80&w=800&auto=format&fit=crop', isOutOfStock: false, quantityRemaining: 20, quantitySold: 38, sizes: ['16GB (2x8GB)', '32GB (2x16GB)', '64GB (2x32GB)'] },
  { id: 33, name: 'Fuente de Poder 850W 80 Plus Gold Full Modular', cat: 'Fuente de poder', department: 'Electrónica', type: 'Fuente de poder', gender: 'General', price: '$135.00', originalPrice: '$175.00', offer: 23, desc: 'Fuente de alimentación con certificación 80 PLUS Gold de alta eficiencia, cables planos completamente modulares y ventilador silencioso de 135mm con rodamientos FDB.', image: 'https://images.unsplash.com/photo-1587202372634-32705e3bf49c?q=80&w=800&auto=format&fit=crop', isOutOfStock: false, quantityRemaining: 10, quantitySold: 22, sizes: ['750W Gold', '850W Gold', '1000W Gold'] },
  { id: 34, name: 'Procesador 8 Núcleos 16 Hilos 5.3GHz Turbo', cat: 'Procesador', department: 'Electrónica', type: 'Procesador', gender: 'General', price: '$319.00', originalPrice: '$399.00', offer: 20, desc: 'Procesador de última generación desbloqueado para overclocking, arquitectura de alto rendimiento para gaming competitivo, streaming y creación de contenido.', image: 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?q=80&w=800&auto=format&fit=crop', isOutOfStock: false, quantityRemaining: 7, quantitySold: 29, sizes: ['Standard Edition', 'Con Disipador'] },
  { id: 35, name: 'Tarjeta Gráfica Gaming 16GB GDDR6X Triple Fan OC', cat: 'Tarjeta gráfica', department: 'Electrónica', type: 'Tarjeta gráfica', gender: 'General', price: '$680.00', originalPrice: '$850.00', offer: 20, desc: 'GPU de máxima potencia para juegos 4K y trazado de rayos (Ray Tracing) en tiempo real con triple ventilador silencioso y backplate metálico reforzado.', image: 'https://images.unsplash.com/photo-1591488320449-011701bb6704?q=80&w=800&auto=format&fit=crop', isOutOfStock: false, quantityRemaining: 5, quantitySold: 18, sizes: ['12GB OC', '16GB OC', '24GB OC'] },
  { id: 36, name: 'Disco Duro SSD M.2 NVMe PCIe 4.0 2TB (7400MB/s)', cat: 'Disco duro', department: 'Electrónica', type: 'Disco duro', gender: 'General', price: '$149.00', originalPrice: '$199.00', offer: 25, desc: 'Unidad de estado sólido NVMe Gen4 de velocidad extrema, lectura secuencial de hasta 7400 MB/s con disipador de calor de grafeno ideal para PC y consolas.', image: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?q=80&w=800&auto=format&fit=crop', isOutOfStock: false, quantityRemaining: 25, quantitySold: 64, sizes: ['1TB NVMe', '2TB NVMe', '4TB NVMe'] },
  { id: 37, name: 'Kit Accesorios: Teclado Mecánico RGB + Ratón Gaming', cat: 'Accesorios', department: 'Electrónica', type: 'Accesorios', gender: 'General', price: '$79.00', originalPrice: '$110.00', offer: 28, desc: 'Combo gaming premium con teclado mecánico con switches intercambiables en caliente y ratón óptico de 16000 DPI con cable paracord ultra flexible.', image: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?q=80&w=800&auto=format&fit=crop', isOutOfStock: false, quantityRemaining: 15, quantitySold: 47, sizes: ['Switches Red (Lineal)', 'Switches Brown (Táctil)', 'Switches Blue (Clicky)'] }
];

